#ifndef SAMPLELIBRARY_GLOBAL_H
#define SAMPLELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAMPLELIBRARY_LIBRARY)
#  define SAMPLELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAMPLELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAMPLELIBRARY_GLOBAL_H
